package com.chase.money.envelopes.data;


import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "envelope")
//@Entity
public class Envelope{
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
   // @Id
   // @GeneratedValue(strategy=GenerationType.AUTO) 
    private Long id;
    @NotNull
    private String category;
    @NotNull
    private Long panId;
}