package com.chase.money.envelopes.data;

import java.math.BigDecimal;
import java.time.Month;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import org.hibernate.validator.constraints.Length;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "monthlyEnvelope")
public class MonthlyEnvelope{

    
    @DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
    private Long id;

    
    @NotNull
    private Long parentId;

    @Enumerated(EnumType.STRING)
    @NotNull
    private Month month;

    @NotNull
    @Min(1970)
    @Max(2990)
    private Long year;

    @Min(0)
    @NotNull
    private BigDecimal total;

    @NotNull
    private BigDecimal remaining;

    @NotNull
    private Long vanId;

    @NotNull
    @Length(max=4,min=4)
    private String lastFour;
    
    @NotNull
    @Length(max=5,min=5)
    private String expDate;

}