package com.chase.money.envelopes.data;

import java.math.BigDecimal;
import java.time.Month;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;

import org.hibernate.validator.constraints.Length;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "monthlyEnvelope")
//@Entity
public class MonthlyEnvelope{

    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    //@Id
    //@GeneratedValue(strategy=GenerationType.AUTO) 
    private String id;

    
    @NotNull
    private String parentId;

    @NotNull
    private String month;

    @NotNull
    @Min(1970)
    @Max(2990)
    private Long year;

    @Min(0)
    @NotNull
    private BigDecimal total;

    @NotNull
    private BigDecimal remaining;

    @NotNull
    private String vanId;

    @NotNull
    @Length(max=4,min=4)
    private String lastFour;
    
    @NotNull
    @Length(max=5,min=5)
    private String expDate;

}